CREATE TABLE customers (
    customer_id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    balance NUMBER,
    LastModified DATE
);

CREATE TABLE transactions (
    txn_id NUMBER PRIMARY KEY,
    customer_id NUMBER,
    txn_date DATE,
    amount NUMBER,
    txn_type VARCHAR2(50)
);

CREATE TABLE auditlog (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    txn_id NUMBER,
    customer_id NUMBER,
    log_time DATE,
    action VARCHAR2(50)
);

INSERT INTO customers VALUES (101, 'Siri', 'siri56@mail.com', 5600, SYSDATE);
INSERT INTO customers VALUES (102, 'Raji', 'raji12@mail.com', 3500, SYSDATE);


CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON transactions
FOR EACH ROW
DECLARE
    v_balance customers.balance%TYPE;
BEGIN
    SELECT balance INTO v_balance FROM customers WHERE customer_id = :NEW.customer_id;

    IF :NEW.txn_type = 'Withdrawal' THEN
        IF :NEW.amount > v_balance THEN
            RAISE_APPLICATION_ERROR(-20001, 'Insufficient balance for withdrawal.');
        END IF;
    ELSIF :NEW.txn_type = 'Deposit' THEN
        IF :NEW.amount <= 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Deposit amount must be positive.');
        END IF;
    END IF;
END;
/


BEGIN
    INSERT INTO transactions VALUES (2, 101, SYSDATE, 2000, 'Withdrawal');
    DBMS_OUTPUT.PUT_LINE('Valid withdrawal is inserted.');

    BEGIN
        INSERT INTO transactions VALUES (3, 101, SYSDATE, 999999, 'Withdrawal');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error (withdrawal): ' || 
                CASE 
                    WHEN SQLCODE = -20001 THEN 'Insufficient balance for withdrawal.'
                    ELSE 'Unexpected error.'
                END);
    END;

    BEGIN
        INSERT INTO transactions VALUES (4, 101, SYSDATE, -500, 'Deposit');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error (deposit): ' || 
                CASE 
                    WHEN SQLCODE = -20002 THEN 'Deposit amount must be positive.'
                    ELSE 'Unexpected error.'
                END);
    END;
END;
/